Update readme.md
RPCSX/rpcsx pull request #4
Opened 2023-07-03 17:34 UTC by upintheairsheep

2023-07-04 10:19 UTC, DHrpcs3 commented
The rest look good

2023-07-04 10:20 UTC, DHrpcs3 requested changes

2023-07-05 00:37 UTC, upintheairsheep commented on readme.md
> +It's NOT possible to run any games yet. It's also unknown when it will become possible. The emulator may support the PlayStation 5 in the future due to its extremely similar hardware and software, si
OK. Remove it.

2023-07-06 22:20 UTC, DHrpcs3 commented
Outdated

2023-07-06 22:20 UTC, closed without merging